# Dev database
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portfolio_db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  phpmyadmin:
    image: dpage/pgadmin4
    container_name: portfolio_pma
    links:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
    ports:
      - 8082:80
