INSERT INTO `Image` (`id`, `full`, `desktop`, `tablet`, `mobile`, `small`, `coeff`, `width`, `created`) VALUES
(2, 'https://storage.yandexcloud.net/jobs/ana/full.png', 'https://storage.yandexcloud.net/jobs/ana/desktop.png', 'https://storage.yandexcloud.net/jobs/ana/tablet.png', 'https://storage.yandexcloud.net/jobs/ana/mobile.png', 'https://storage.yandexcloud.net/jobs/ana/small.png', 1.7777777777777777, 1920, '2025-03-26 07:22:24.342'),
(3, 'https://storage.yandexcloud.net/jobs/uyem1.gif', 'https://storage.yandexcloud.net/jobs/uyem1.gif', 'https://storage.yandexcloud.net/jobs/uyem1.gif', 'https://storage.yandexcloud.net/jobs/uyem1.gif', 'https://storage.yandexcloud.net/jobs/uyem1.gif', 1.7777777777777777, 640, '2025-03-26 07:40:02.690'),
(6, 'https://storage.yandexcloud.net/jobs/conhos/full.png', 'https://storage.yandexcloud.net/jobs/conhos/desktop.png', 'https://storage.yandexcloud.net/jobs/conhos/tablet.png', 'https://storage.yandexcloud.net/jobs/conhos/mobile.png', 'https://storage.yandexcloud.net/jobs/conhos/small.png', 1.7777777777777777, 1920, '2025-03-26 08:14:35.660'),
(7, 'https://storage.yandexcloud.net/jobs/automatic/full.png', 'https://storage.yandexcloud.net/jobs/automatic/desktop.png', 'https://storage.yandexcloud.net/jobs/automatic/tablet.png', 'https://storage.yandexcloud.net/jobs/automatic/mobile.png', 'https://storage.yandexcloud.net/jobs/automatic/small.png', 0.24055113133611428, 1903, '2025-03-26 08:27:47.205');

INSERT INTO `Job` (`id`, `priority`, `name`, `link`, `description`, `archive`, `imageId`, `lang`, `created`) VALUES
('12', 2, 'Application for learning foreign languages', 'https://github.com/kolserdav/ana', 'An open-source app that uses AI (Libre Translate) to help the user create sentences in the target language. It also allows you to save them and listen to them using speech synthesis. Before it was shut down, it was available on FDroid.', 0, 2, 'en', '2025-03-26 07:27:36.852'),
('13', 3, 'Online call to add to the site', 'https://github.com/kolserdav/sfu-react', 'Developed a React component and open-source server that allows you to add multi-participant video call functionality to your website. Based on WebRTC technology.', 0, 3, 'en', '2025-03-26 07:40:34.995'),
('16', 1, 'Container Hosting', 'https://conhos.ru', 'A cloud service for hosting Docker containers has been developed and supported.', 0, 6, 'en', '2025-03-26 08:17:02.167'),
('17', 7, 'Automation of business processes', 'https://github.com/kolserdav/automatic', 'Made a website for self-promotion. At the moment, the source code of the site is open.', 0, 7, 'en', '2025-03-26 08:30:11.101'),
('2', 2, 'Приложение для изучения иностранных языков', 'https://github.com/kolserdav/ana', 'Приложение с открытым исходным кодом, которое на основе ИИ (Libre Translate) помогает пользователю составлять предложения на изучаемом языке. А также позволяет сохранять их и прослушивать с помощью синтеза речи. До того как было свернуто, было доступно на FDroid.', 0, 2, 'ru', '2025-03-26 07:27:36.852'),
('3', 3, 'Звонилка на сайт', 'https://github.com/kolserdav/sfu-react', 'Разработал React компонент и сервер с открытым исходным кодом, который позволяет добавлять на сайт функционал видеозвонка с несколькими участниками. На основе технологии WebRTC.', 0, 3, 'ru', '2025-03-26 07:40:34.995'),
('6', 1, 'Контейнерный Хостинг', 'https://conhos.ru', 'Разработан и поддерживается облачный сервис для размещения Docker контейнеров.', 0, 6, 'ru', '2025-03-26 08:17:02.167'),
('7', 7, 'Автоматизация бизнес процессов', 'https://github.com/kolserdav/automatic', 'Делал сайт для саморекламы. В данный момент, исходный код сайта открыт.', 0, 7, 'ru', '2025-03-26 08:30:11.101');

INSERT INTO `PageIndex` (`id`, `metaTitle`, `metaDescription`, `metaKeywords`, `headerTitle`, `headerSubtitle`, `headerDescription`, `aboutTitle`, `aboutSubtitle`, `personalTitle`, `personalDescription`, `techTitle`, `techDescription`, `sliderTitle`, `sliderDescription`, `cloudTitle`, `cloudContent`, `lang`, `created`) VALUES
(1, 'Портфолио программиста', 'Демонстрация опыта работы разработчика ПО Кольмиллер Сергея', 'node, фрилансер', 'Портфолио программиста', 'Демонстрация работ разработчика ПО Кольмиллер Сергея', 'Сложное состоит из простого, а великое из мáлого', 'Обо мне', 'Биография в ИТ (коротко)', 'Кольмиллер Сергей', 'В ИТ с 2010 года, создавал сайты на CMS, совмещая с основной работой.\r\nПрограммировать начал с 2017 года, после того как закончил курсы по основам программирования. С того времени ничем, кроме разработки не занимался.', 'Навыки в технологиях', 'Это далеко не полный список моих навыков. Здесь указаны только те, с которыми работаю чаще всего.', 'Работы', 'Это не полный список проектов в которых я принимал участие. Показаны только самые интересные и те в разработке которых я играл ключевую роль.', 'Облачный сервис', 'Для размещения приложений в сети, я использовал множество разных сервисов. Но теперь я создал свой сервис, в котором размещаю все свои проекты, в том числе и этот сайт. Контейнерый Хостинг это удобный и недорогой хостинг на основе Docker контейнеров.', 'ru', '2025-03-24 03:57:49.239'),
(2, 'Programmer portfolio', 'Demonstration of the work experience of software developer Kolmiller Sergei', 'node, freelancer', 'Programmer portfolio', 'Demonstration of the works of software developer Kolmiller Sergei', 'The complex consists of the simple, and the great of the small', 'About me', 'Biography in IT (short)', 'Kolmiller Sergei', 'In IT since 2010, created websites on CMS, combining it with his main job.\r\nStarted programming in 2017, after completing courses on the basics of programming. Since then, I have not done anything except development.', 'Skills in technology', 'This is far from a complete list of my skills. Here are listed only those that I work with most often.', 'Jobs', 'This is not a complete list of projects I took part in. Only the most interesting ones are shown, and those in the development of which I played a key role.', 'Cloud service', 'To host applications on the network, I used many different services. But now I have created my own service, where I host all my projects, including this site. Container Hosting is a convenient and inexpensive hosting based on Docker containers.', 'en', '2025-03-24 03:57:49.239');

INSERT INTO `PageResume` (`id`, `metaTitle`, `metaDescription`, `metaKeywords`, `printVersion`, `lang`) VALUES
(1, 'Резюме Сергей Кольмиллер', 'Мое актуальное резюме', 'резюме', 'ru', ''),
(2, 'Resume Sergei Kolmiller', 'My current resume', 'resume', 'en', '');

INSERT INTO `Tech` (`id`, `title`, `description`, `pageId`, `lang`, `created`) VALUES
(1, 'Бекенд', 'Node JS, Express, Fastify, WS, Prisma JS, Docker, Kubernetes', 1, 'ru', '2025-03-24 04:07:53.314'),
(2, 'Фронтенд', 'ReactJS, Next.js', 1, 'ru', '2025-03-26 06:22:58.147'),
(3, 'Языки программирования', 'Javascript + jsdoc, Typescript', 1, 'ru', '2025-03-26 06:24:06.578'),
(4, 'Операционные системы', 'Linux, Windows', 1, 'ru', '2025-03-26 06:27:26.467'),
(5, 'Браузеры', 'Firefox, Chrome, Safari', 1, 'ru', '2025-03-26 06:28:37.135'),
(6, 'Backend', 'Node JS, Express, Fastify, WS, Prisma JS, Docker, Kubernetes', 1, 'en', '2025-03-24 04:07:53.314'),
(7, 'Frontend', 'ReactJS, Next.js', 1, 'en', '2025-03-26 06:22:58.147'),
(8, 'Programming languages', 'Javascript + jsdoc, Typescript', 1, 'en', '2025-03-26 06:24:06.578'),
(9, 'Operationing systems', 'Linux, Windows', 1, 'en', '2025-03-26 06:27:26.467'),
(10, 'Browsers', 'Firefox, Chrome, Safari', 1, 'en', '2025-03-26 06:28:37.135');

INSERT INTO `_prisma_migrations` (`id`, `checksum`, `finished_at`, `migration_name`, `logs`, `rolled_back_at`, `started_at`, `applied_steps_count`) VALUES
('5d1553a4-0d01-421b-8840-8096a0fc0053', '60a0c66111a92e8c31ff659392cfa8c5fbc65df8533a838229882b41fa541beb', '2026-10-01 08:17:47.719', '20261001081747', NULL, NULL, '2026-10-01 08:17:47.577', 1),
('ca7a5db9-2967-4110-a2ff-1bdd067b20fe', 'fc5df71c8b7fb9f3f761a693158dc7c2efaebc35ee887276b21b3be19bcbd1ab', '2026-10-01 08:21:08.889', '20261001082108', NULL, NULL, '2026-10-01 08:21:08.860', 1);

