-- AlterTable
ALTER TABLE `Image` MODIFY `full` VARCHAR(100) NOT NULL,
    MODIFY `desktop` VARCHAR(100) NOT NULL,
    MODIFY `tablet` VARCHAR(100) NOT NULL,
    MODIFY `mobile` VARCHAR(100) NOT NULL,
    MODIFY `small` VARCHAR(100) NOT NULL;
