/******************************************************************************************
 * Repository: https://github.com/kolserdav/portfolio.git
 * Author: Sergey Kolmiller
 * Email: <serega12101983@gmail.com>
 * License: Специальная
 * License Text: Права на копирование и распостранение данного файла или его частей имеет только владелец указанного репозитория
 * Copyright: kolserdav, All rights reserved (c)
 * Create date: Sat Nov 27 2021 03:15:33 GMT+0700 (Krasnoyarsk Standard Time)
 ******************************************************************************************/
import { useRef, useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import clsx from 'clsx';
import Image from 'next/image';
import { Swiper, GetSwipeHandler, Swipe } from '@kolserdav/swiper';
import '@kolserdav/swiper/dist/index.css';
import styles from '../styles/Index.module.scss';

const getNext: GetSwipeHandler = async (old) => {
  const id = old + 1;
  return {
    id: id < 7 ? id : null,
    children: id < 7 ? <h1>Test {id}</h1> : <div />,
  };
};

const getPrevios: GetSwipeHandler = async (old) => {
  const id = old - 1;
  return {
    id: id > 0 ? id : null,
    children: id > 0 ? <h1>Test {id}</h1> : <div />,
  };
};

const Home: NextPage = () => {
  const nextRef = useRef<HTMLButtonElement>(null);
  const prevRef = useRef<HTMLButtonElement>(null);
  const [current, setCurrent] = useState<Swipe>();

  useEffect(() => {
    if (!current) {
      (async () => {
        setCurrent(await getNext(1));
      })();
    }
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={clsx(styles.main, styles.row)}>
        <div className={styles.swiper}>
          {current && (
            <Swiper
              defaultCurrent={current}
              getNext={getNext}
              getPrev={getPrevios}
              invitationAnimation={true}
            />
          )}
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export default Home;
