/******************************************************************************************
 * Repository: https://github.com/kolserdav/portfolio.git
 * Author: Sergey Kolmiller
 * Email: <serega12101983@gmail.com>
 * License: Специальная
 * License Text: Права на копирование и распостранение данного файла или его частей имеет только владелец указанного репозитория
 * Copyright: kolserdav, All rights reserved (c)
 * Create date: Sat Nov 27 2021 03:15:33 GMT+0700 (Krasnoyarsk Standard Time)
 ******************************************************************************************/
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Index.module.scss';
import Swiper, { GetSwipeHandler } from '../components/ui/Swiper';

const getNext: GetSwipeHandler = (old: number) => {
  const id = old + 1;
  return {
    id,
    children: <>Test {id}</>,
  };
};

const getPrevios: GetSwipeHandler = (old: number) => {
  const id = old - 1;
  return {
    id,
    children: <h1>Test {id}</h1>,
  };
};

const _getNext = (id: number): Awaited<ReturnType<GetSwipeHandler>> => {
  const res: any = getNext(id);
  return res;
};

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <div className={styles.swiper}>
        <Swiper
          current={_getNext(0)}
          prev={_getNext(-1)}
          next={_getNext(1)}
          getNext={getNext}
          getPrev={getPrevios}
        />
      </div>
    </main>
    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
);
export default Home;
